### ISSUE TITLE
Table object  created in icub environment 

### ISSUE THREAD

**Issue by ArfnZl** [robotology/robotology-superbuild#1001]
Please  provide  example  created object  table in icub environment

**Comment by ArfnZl** [comment]
@traversaro sir please provide  example  create object table in icub environment

**Comment by traversaro** [comment]
Hi @ArfnZl, do you mean on iCub simulation in Gazebo, or using the old `iCub_SIM`?

**Comment by ArfnZl** [comment]
Old icub simulation

**Comment by traversaro** [comment]
Then you can find some information in http://wiki.icub.org/wiki/Simulator_README#OBJECT_MANIPULATION: .

**Comment by traversaro** [comment]
Hi @ArfnZl, feel free to open new issues if you have more doubts.
