### ISSUE TITLE
Fingers joints move yarp icub through  python

### ISSUE THREAD

**Issue by ArfnZl** [robotology/robotology-superbuild#1056]
Please  provide  python yarp icub code to move icub fingers joints move....i want to move fingers joint in yarp icub simulator  through  python code

**Comment by ArfnZl** [comment]
@traversaro  please  help me

**Comment by ArfnZl** [comment]
@traversaro 
Please  help. Me

**Comment by traversaro** [comment]
Hi @ArfnZl, can you please open a question in https://github.com/robotology/community/discussions/categories/q-a ? This issue tracker is devoted for specific issues in robotology-superbuild, thanks.

**Comment by traversaro** [comment]
Moved to https://github.com/robotology/community/discussions/572 .
