### ISSUE TITLE
Icub object gripping  problem 

### ISSUE THREAD

**Issue by ArfnZl** [robotology/robotology-superbuild#1098]
Dear i am trying to grip the ball but when hand touches it slipped kindly guide how to resolve this slipping problem... I am using pyhon anaconda with i cub...i have tried many DoF

**Comment by ArfnZl** [comment]
https://user-images.githubusercontent.com/83446699/163709888-a5a16a5d-162c-4909-aac8-04c9f9b58e4c.mp4

**Comment by ArfnZl** [comment]
@traversaro please  sir

**Comment by traversaro** [comment]
Hi @ArfnZl, as I already explained in https://github.com/robotology/robotology-superbuild/issues/1082#issuecomment-1087230288: 
* This repo is not meant for general question on iCub, for that post on https://github.com/robotology/community/discussions 
* If you want to help on some case, it is much more probable that you will receive a reply if you provide the code you are working on.
