### ISSUE TITLE
Gazebo models installed by icub-models are not available in Gazebo after installing the robotology-superbuild 

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#111]
I just realized discussing with @pattacini that the Gazebo models installed by `icub-models` are not available in Gazebo, because in the superbuild docs and setup.sh file we do not add to `GAZEBO_MODEL_PATH` the  directories `<prefix>/share/iCub` and `<prefix>`, as documented in https://github.com/robotology/icub-models#use-the-models-with-gazebo . 
To avoid confusion to superbuild users, perhaps we  should first solve  https://github.com/robotology/icub-models/issues/11 ? 
@diegoferigo @gabrielenava

**Comment by diegoferigo** [comment]
> To avoid confusion to superbuild users, perhaps we should first solve robotology/icub-models#11 ?

Yes, I would proceed in this direction

**Comment by diegoferigo** [comment]
cc @nunoguedelha

**Comment by traversaro** [comment]
> I am not a user of setup.sh since I prefer to manually set the paths in the .bashrc, and I didn't note that the setup.sh was not up to date

I see, but consider that also the docs to write your own `setup.sh` are missing that part.

**Comment by gabrielenava** [comment]
Given that https://github.com/robotology/icub-models#use-the-models-with-gazebo is now closed, I may take this issue and fix the setup.sh if there are no other reasons for waiting.

**Comment by traversaro** [comment]
I do not think anything else is blocking the issue.

**Comment by gabrielenava** [comment]
Fixed with this commit: https://github.com/robotology/robotology-superbuild/commit/32c56bc2d390023f5e16dc09776039f648fa1067

Closing the issue.
