### ISSUE TITLE
Deprecate ROBOTOLOGY_USES_OCULUS_SDK  and yarp-device-ovrheadset 

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1114]
Since we are working on switching the VR support to OpenXR (https://github.com/robotology/robotology-superbuild/issues/1113) I was wondering if we can deprecate and eventually remove the `ROBOTOLOGY_USES_OCULUS_SDK` option and the [`yarp-device-ovrheadset` repo](https://github.com/robotology/yarp-device-ovrheadset). 

Is anyone still using this option @S-Dafarra @randaz81 ?

**Comment by S-Dafarra** [comment]
From the AMI teleoperation side, it was used last time for a demo in September. There is no drop-in replacement for ``yarp-device-ovrheadset``, but I agree in removing the option from the superbuild.

**Comment by traversaro** [comment]
> I think it is fair to announce that it is deprecated in 2022.05 and remove it in 2022.08 .

We never announced that, but I think there is no problem in removing it.
