### ISSUE TITLE
Pressure tactile sensors is not reading valued

### ISSUE THREAD

**Issue by ArfnZl** [robotology/robotology-superbuild#1119]
Hey.. I am working  on icub yarp python.. I want to add tactile  pressure  sensors for measure gripping  force...i also added tactile sensors which is showing 0,255 valued only... My project is gripping object but object is slipping 
Problem............. 
Please  provide me python code of pressure tactile  sensors for measure  gripping  force... 
![Screenshot_2022-05-15-16-24-18-87](https://user-images.githubusercontent.com/83446699/168470367-04a8dd45-262a-45b8-8f40-8d71552f26e2.png)
![Uploading Screenshot_2022-05-15-16-24-53-78.png…]()

**Comment by ArfnZl** [comment]
![Uploading Screenshot_2022-05-15-16-24-53-78.png…]()

**Comment by ArfnZl** [comment]
![Screenshot_2022-05-15-16-24-53-78](https://user-images.githubusercontent.com/83446699/168470490-93bb585a-770f-44f0-97e5-af57a4fefb1d.png)

**Comment by traversaro** [comment]
Hi @ArfnZl, as I already explained in https://github.com/robotology/robotology-superbuild/issues/1098#issuecomment-1102618534 and https://github.com/robotology/robotology-superbuild/issues/1082#issuecomment-1087230288 : 

> * This repo is not meant for general question on iCub, for that post on https://github.com/robotology/community/discussions 
> * If you want to help on some case, it is much more probable that you will receive a reply if you provide the code you are working on.

So, please open an issue in https://github.com/robotology/community/discussions and provide the code you are running to simplifying the life of people that may want to help you, thanks.
