### ISSUE TITLE
Tactile pressure sensors

### ISSUE THREAD

**Issue by ArfnZl** [robotology/robotology-superbuild#1188]
Hello
Sir i want to add pressure sensors for measure grasping  force in icub yarp through  python spyder please provide me code of pressure  sensors

**Comment by traversaro** [comment]
Hi @ArfnZl, can you reply on the questions asked in:

* https://github.com/robotology/robotology-superbuild/issues/1098#issuecomment-1102618534 
* https://github.com/robotology/robotology-superbuild/issues/1082#issuecomment-1087230288
* https://github.com/robotology/robotology-superbuild/issues/1056#issuecomment-1060677969
* https://github.com/robotology/robotology-superbuild/issues/1119#issuecomment-1126935169

To be honest, it is not completly polite to continue to open new issues without replying to old ones.
