### ISSUE TITLE
Documentation – Problems with setting `DISPLAY` on WSL2

### ISSUE THREAD

**Issue by pattacini** [robotology/robotology-superbuild#1332]
The documentation for WSL2 says that `DISPLAY` should be set pointing to the host as follows:

https://github.com/robotology/robotology-superbuild/blob/a7cdb9e15ce0525c0b7e61837a59e410836df144/README.md?plain=1#L174

However, applications such as `yarpview` and `gazebo` won't run correctly this way on my WSL2 system.
I didn't seem to catch error messages though.

By contrast, leaving the env var `DISPLAY` unset and thus equal to its original value (i.e., `:0`) makes the apps work again.

@traversaro, did you happen to come across the same behavior?

cc @martinaxgloria @davidelasagna

**Comment by traversaro** [comment]
Thanks for the feedback @pattacini ! This is kind of related to https://github.com/robotology/robotology-superbuild/issues/1190 .

**Comment by pattacini** [comment]
@traversaro, you can close this as a duplicate then 👍🏻

**Comment by traversaro** [comment]
Ok! Let's continue the discussion in https://github.com/robotology/robotology-superbuild/issues/1190 .
