### ISSUE TITLE
Add tomlplusplus as a blf dependency

### ISSUE THREAD

**Issue by LoreMoretti** [robotology/robotology-superbuild#1363]
To use the latest features of blf that are covered by tutorials such as https://github.com/ami-iit/bipedal-locomotion-framework/blob/master/examples/InverseKinematics/inverse_kinematics.ipynb , we need to make sure that the blf in the superbuild is already compiled with tomlplusplus support, that is currently not the case.

**Comment by GiulioRomualdi** [comment]
Here the project https://github.com/marzer/tomlplusplus

Since tomlplusplus is a private header only dependency of blf we may think to fetch content  in blf instead of having it in the superbuild.

What do you think?

**Comment by S-Dafarra** [comment]
You could have an option to use a system version of it (possible snippet: https://github.com/ami-iit/yarp-device-openxrheadset/blob/7142de033592960717ba0761042617572dfd9c44/CMakeLists.txt#L74-L88), but since it is a private header that needs to be compiled, I am not sure it is even necessary
