### ISSUE TITLE
Release v2023.02.1

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1368]
We would like to release v2023.02.1 with:
* ergocub-software correctly released to v0.2.0 (see https://github.com/robotology/robotology-superbuild/pull/1364)
* tomlplusplus support in blf (see https://github.com/robotology/robotology-superbuild/issues/1363)

@Nicogene do you have any specific opinion on this?

**Comment by Nicogene** [comment]
> We would like to release v2023.02.1 with:
> 
>     * ergocub-software correctly released to v0.2.0 (see [Fix ergocub-software branch used in ProjectsTagsStable.cmake #1364](https://github.com/robotology/robotology-superbuild/pull/1364))
> 
>     * tomlplusplus support in blf (see [Add tomlplusplus as a blf dependency #1363](https://github.com/robotology/robotology-superbuild/issues/1363))
> 
> 
> @Nicogene do you have any specific opinion on this?

Ok for me! We can proceed without making any announcement, maybe a comment in the 2023.02.0 announcement

**Comment by traversaro** [comment]
Done in https://github.com/robotology/robotology-superbuild/releases/tag/v2023.02.1 .
