### ISSUE TITLE
Travis CI on macOS is broken

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#141]
It is the usual problem `brew install package` fails if a package is already installed. In the past @francesco-romano solved it with a script that checked if a package was installed or not, but I think the best option (as recommended by brew's author: https://discourse.brew.sh/t/skip-ignore-brew-install-if-package-is-already-installed/633 ) is probably to just add a `Brewfile` to the repo (that we can also use in the macOS installation instructions) and just use that for installing dependencies also in Travis. 

cc @DanielePucci

**Comment by DanielePucci** [comment]
Maybe @lrapetti can take upon this?

**Comment by drdanz** [comment]
Have you seen the [homebrew travis addon](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-os-x)? I fixed all the issues with travis on macos in YARP by installing the packages with the addon rather than manually.

**Comment by traversaro** [comment]
@drdanz Thanks! That is even better.

**Comment by lrapetti** [comment]
> Maybe @lrapetti can take upon this?

@traversaro
I may take upon this issue

**Comment by traversaro** [comment]
GREAT! Let me know if you need any help. I think that @drdanz pointer is a great starting point, even if I am not sure how it interact with the multi-stage stuff that @diegoferigo originally used for WB-Toolbox and that we copy&pasted around in https://github.com/robotology/robotology-superbuild/pull/108 .

**Comment by traversaro** [comment]
Relevant issue for using bundle: https://github.com/Homebrew/homebrew-bundle/issues/313 . @lrapetti
