### ISSUE TITLE
Add bayes-filters-lib

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1410]

**Comment by GiulioRomualdi** [comment]
Hi @traversaro thank you for opening the issue.  
In which profile you would like to add it?

**Comment by GiulioRomualdi** [comment]
@isorrentino

**Comment by GiulioRomualdi** [comment]
After discussing with @traversaro we decided to add it in `dynamics_full_deps` 
I will proceed with the PR
