### ISSUE TITLE
Bug in OpenCV binaries distributed by YARP installer

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#145]
See https://github.com/robotology/icub-packaging/issues/10 . 

@GiulioRomualdi

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer for reporting the issue.

**Comment by traversaro** [comment]
We can close this after https://github.com/robotology/robotology-superbuild/pull/348 has been merged, as we will stop relying on those installers for opencv.

**Comment by GiulioRomualdi** [comment]
Probably It may be close
