### ISSUE TITLE
Report opencv + Eigen 3.4.1 problem

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1453]
See https://github.com/robotology/robotology-superbuild/issues/1446#issuecomment-1658633500, ideally before the Eigen 3.4.1 release .

**Comment by jeanchristopheruel** [comment]
I just made a Pull Request to address the issue.
https://github.com/opencv/opencv/pull/24513

**Comment by traversaro** [comment]
I reported the issue to Eigen mantainers with the details @jeanchristopheruel kindly provided in https://gitlab.com/libeigen/eigen/-/issues/2745 .

**Comment by traversaro** [comment]
> I reported the issue to Eigen mantainers with the details @jeanchristopheruel kindly provided in https://gitlab.com/libeigen/eigen/-/issues/2745 .

And proposed a fix in https://gitlab.com/libeigen/eigen/-/merge_requests/1412, thanks @jeanchristopheruel !

**Comment by traversaro** [comment]
As the error in itself is tracked on the Eigen bugtracker, I will close the issue here.
