### ISSUE TITLE
Problem with suberbuild on matlab

### ISSUE THREAD

**Issue by fils99** [robotology/robotology-superbuild#1463]
I have found the following error using superbuild on matlab:

![image](https://github.com/robotology/robotology-superbuild/assets/125360921/4880cd33-5932-4de6-81f2-a698bc4c00b2)

Any suggestions?

**Comment by traversaro** [comment]
Yes. In a nutshell, it should be sufficient to run:
~~~
sudo aptinstall matlab-support
~~~
and specify your MATLAB installation directory and when there is the question "Rename MATLAB's GCC libraries?" answer "Yes".

If there are no configuration question when you run , probably that means that the package is already installed. In that case, you can just reconfigure it with the command:
~~~
sudo dpkg-reconfigure matlab-support
~~~
and again, specify your MATLAB installation directory and when there is the question "Rename MATLAB's GCC libraries?" answer "Yes".


See https://github.com/robotology/robotology-superbuild/issues/64 for more background on the problem.

**Comment by traversaro** [comment]
I opened a PR to add this information in the documentation: https://github.com/robotology/robotology-superbuild/pull/1464 .
