### ISSUE TITLE
yarpmanager cluster not working

### ISSUE THREAD

**Issue by fvannu** [robotology/robotology-superbuild#1504]
Ciao!

We have a couple of problems with yarpmanager in the superbuild (latest yarp version 3.8.1) on ubuntu 20.04.6 LTS.
When we try to start a node from the cluster manager in yarpmanager, it says "yarprun succesfully executed on node", but actually nothing happens.
If we try to execute a command in the bar and hit "execute" (e.g. yarprun), the terminal log of yarpmanager says "bash: yarprun: command not found". The same commands launched from terminal work fine, we tried also to execute "env" on a terminal the result is this:
![Screenshot from 2023-10-18 14-18-52](https://github.com/robotology/robotology-superbuild/assets/23313360/aea877aa-2196-40bf-a647-a82cdef0e4cb)

while sending the "env" command from the yarpmanager box gives this result instead:
![Screenshot from 2023-10-18 14-20-36](https://github.com/robotology/robotology-superbuild/assets/23313360/55154c71-2d7f-40e1-aaa6-e3c5211e99d1)

In addition, we can't find from which cluster-config.xml file our cluster is built.

Do you have any idea no how to solve these issues?

**Comment by traversaro** [comment]
Hi @fvannu , this problem does not seem to be strictly related to robotology-superbuild, did you consider asking this question on https://github.com/orgs/robotology/discussions/categories/q-a ?

**Comment by fvannu** [comment]
I’ll try there then, thanks a lot Silvio!
