### ISSUE TITLE
Enable COMPILE_ergoCubEmotions  in ergocub-software

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1513]
@Nicogene @martinaxgloria should we enable the `COMPILE_ergoCubEmotions` CMake option in ergocub-software in robotology-superbuild? Or that CMake options is enabled/documented somewhere else in ergocub docs?

**Comment by traversaro** [comment]
There is also  [`ergocub-fingers-tuning`](https://github.com/icub-tech-iit/ergocub-software/tree/master/src/tools/ergocub-fingers-tuning) but I guess that is not need for the "normal" use of the robot?

**Comment by martinaxgloria** [comment]
Hi @traversaro,

if I remember well, it is not enabled by default. Moreover, there is little documentation in the [README.md](https://github.com/icub-tech-iit/ergocub-software/blob/master/src/modules/ergoCubEmotions/README.md) of the ergoCubEmotions module inside `ergocub-software`, and it is also documented [here](https://icub-tech-iit.github.io/ergocub-software/ergoCubEmotions/). Maybe we can link this documentation within `icub-tech-docs` under the ergocub sw part

**Comment by mfussi66** [comment]
> There is also [`ergocub-fingers-tuning`](https://github.com/icub-tech-iit/ergocub-software/tree/master/src/tools/ergocub-fingers-tuning?rgh-link-date=2023-10-31T10%3A02%3A20Z) but I guess that is not need for the "normal" use of the robot? fyi @mfussi66

I can confirm, not used during normal operations.

**Comment by traversaro** [comment]
If `ergoCubEmotions` is used for the normal operation of the robot, perhaps we can enable it by default at least in the superbuild (perhaps guarded by the `ROBOTOLOGY_ENABLE_ICUB_HEAD` option)? So users can just install the robotology-superbuild, and start using the robot, instead of having to manually do some steps (and manual steps can quickly became difficult to manage). 

To clarify, I am happy to do the modifications in the robotology-superbuild myself, I just want to make sure that affected people are aligned on this.

**Comment by martinaxgloria** [comment]
> Maybe we can link this documentation within `icub-tech-docs` under the ergocub sw part

And/or we could set this flag ON by default so that the module is always installed

**Comment by martinaxgloria** [comment]
> If `ergoCubEmotions` is used for the normal operation of the robot, perhaps we can enable it by default at least in the superbuild (perhaps guarded by the `ROBOTOLOGY_ENABLE_ICUB_HEAD` option)? So users can just install the robotology-superbuild, and start using the robot, instead of having to manually do some steps (and manual steps can quickly became difficult to manage).

I agree :+1:

**Comment by traversaro** [comment]
Ok, do we want to enable the option in the superbuild or in ergocub-softare ? cc @Nicogene

**Comment by pattacini** [comment]
> Ok, do we want to enable the option in the superbuild or in ergocub-softare ? cc @Nicogene

I would do this upstream, in `ergocub-software`.

**Comment by Nicogene** [comment]
`ergoCubEmotions` requires `YARP` and `OpenCV`, I thought to put it as OFF as default in order to minimize the required dependencies for those who need just to install the urdf of the robots.
We can make it as default but we have to change the documentation in order to install YARP and OpenCV.
On the other hand, making it ON in the superbuild would have less impact in my opinion since YARP and OpenCV are already required by other repositories

**Comment by traversaro** [comment]
@Nicogene do we have any update on this decision? I am fine with both options.

**Comment by pattacini** [comment]
I'm fine also with your option @Nicogene 👍🏻

**Comment by Nicogene** [comment]
> @Nicogene do we have any update on this decision? I am fine with both options.

I think we can takle this next sprint alongside the installation of app xml also when `COMPILE_ergoCubEmotions` is off @martinaxgloria

**Comment by martinaxgloria** [comment]
> > @Nicogene do we have any update on this decision? I am fine with both options.
> 
> I can proceed w/ a PR!

So, with this PR the flag is enabled by default and the module is installed at the superbuild level? Is it protected by the ROBOTOLOGY_ENABLE_ICUB_HEAD flag?

**Comment by Nicogene** [comment]
> > > @Nicogene do we have any update on this decision? I am fine with both options.
> > 
> > 
> > I can proceed w/ a PR!
> 
> So, with this PR the `COMPILE_ergocCubEmotions` option is enabled by default and the module is installed at the superbuild level? Is it protected by the ROBOTOLOGY_ENABLE_ICUB_HEAD flag?

I personally don't have a strong opinion on this, since it is used only in ergoCub, and the option called `ICUB_HEAD` is a bit strange but we don't have and don't want to have yet another option called `ROBOTOLOGY_ENABLE_ERGOCUB_HEAD` just for this executable.
I don't see pros or cons to either option but if you prefer to make it dependent on the ROBOTOLOGY_ENABLE_ICUB_HEAD flag I change it in the PR!

**Comment by pattacini** [comment]
>I don't see pros or cons to either option but if you prefer to make it dependent on the ROBOTOLOGY_ENABLE_ICUB_HEAD flag I change it in the PR!

Maybe, there are scenarios where we want to install it on a laptop for testing purposes.

**Comment by martinaxgloria** [comment]
I agree with your solution @Nicogene, I was only asking for information. Thanks!

**Comment by traversaro** [comment]
> > I don't see pros or cons to either option but if you prefer to make it dependent on the ROBOTOLOGY_ENABLE_ICUB_HEAD flag I change it in the PR!
> 
> Maybe, there are scenarios where we want to install it on a laptop for testing purposes so the guard would be counterproductive.

I totally agree that it is ok not to guard this on `ROBOTOLOGY_ENABLE_ICUB_HEAD`, but just for general knoledge, `ROBOTOLOGY_ENABLE_ICUB_HEAD` options should work totally fine on laptops for testing (it even works on Windows and macOS).

> I personally don't have a strong opinion on this, since it is used only in ergoCub, and the option called ICUB_HEAD is a bit strange but we don't have and don't want to have yet another option called ROBOTOLOGY_ENABLE_ERGOCUB_HEAD just for this executable.

Just fyi, I guess `ROBOTOLOGY_ENABLE_ICUB_HEAD` needs to be enabled also on ergocub-head as it compiles all the embObj devices.

**Comment by Nicogene** [comment]
> Just fyi, I guess ROBOTOLOGY_ENABLE_ICUB_HEAD needs to be enabled also on ergocub-head as it compiles all the embObj devices.

Actually it doesn't because to `ergocub-head` there are attached only the realsense and lidar, that profile has to be enabled on `ergocub-torso` instead, for this reason I was not thinking about adding that option under `ROBOTOLOGY_ENABLE_ICUB_HEAD `

**Comment by traversaro** [comment]
> > Just fyi, I guess ROBOTOLOGY_ENABLE_ICUB_HEAD needs to be enabled also on ergocub-head as it compiles all the embObj devices.
> 
> Actually it doesn't because to `ergocub-head` there are attached only the realsense and lidar, that profile has to be enabled on `ergocub-torso` instead, for this reason I was not thinking about adding that option under `ROBOTOLOGY_ENABLE_ICUB_HEAD `

Ah sorry, yes I mixed up ergocub-head and ergocub-torso . Any suggestion for a better name for `ROBOTOLOGY_ENABLE_ICUB_HEAD` are welcome.
