### ISSUE TITLE
Add teleoperation profile to the continuous integration

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#170]

**Comment by kouroshD** [comment]
cc @kouroshD I will add it later.

**Comment by traversaro** [comment]
Fixed by @kouroshD  in https://github.com/robotology/robotology-superbuild/pull/168 .

**Comment by traversaro** [comment]
> 
> 
> Fixed by @kouroshD in #168 .

No, the issue was about adding it to the continuos integration, and apparently the profile is still not tested there.
