### ISSUE TITLE
Remove IHMC profile

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#182]
Development of https://github.com/robotology-playground/ihmc-ors-yarp is de-facto suspended. To reduce the complexity of superbuild docs, I think we could remove the IHMC profile from the superbuild.
What do you think @gabrielenava @fiorisi ?

**Comment by gabrielenava** [comment]
I agree.

**Comment by fiorisi** [comment]
Ok also for me.

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robotology-superbuild/pull/200 .
