### ISSUE TITLE
icub-tests configuration failed due to missing YARP::YARP_math imported target

### ISSUE THREAD

**Issue by triccyx** [robotology/robotology-superbuild#192]
Tring to compile using the superbuild I face this error.
(pull from master)

```
CMake Error at /home/ltricerri/robotology-superbuild/build/install/lib/cmake/YARP/YARPConfig.cmake:183 (find_package):
  Found package configuration file:

    /home/ltricerri/robotology-superbuild/build/install/lib/cmake/YARP_manager/YARP_managerConfig.cmake

  but it set YARP_manager_FOUND to FALSE so package "YARP_manager" is
  considered to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  YARP::YARP_math

Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by traversaro** [comment]
Reproducible on Travis: https://travis-ci.org/robotology/robotology-superbuild/jobs/514246582 .

**Comment by traversaro** [comment]
Workaround for the issue provided in https://github.com/robotology/icub-tests/pull/46 .

**Comment by traversaro** [comment]
As the fix for this have been merged in https://github.com/robotology/icub-tests/pull/46 and the related YARP issue has been reported in https://github.com/robotology/yarp/issues/1989 , I think we can close this issue.
