### ISSUE TITLE
Installation fails with Mojave MAC os

### ISSUE THREAD

**Issue by claudia-lat** [robotology/robotology-superbuild#228]
I tried to build the latest version of robotology-superbuild on the new Mojave MAC os. It fails with the following error:

```bash
-- Found YARP: /Users/claudialatella/src/robotology-superbuild/build/install/lib/cmake/YARP (found version "3.2.0")
-- YARP is version: 3.2.0
CMake Error at CMakeLists.txt:23 (message):
  YARP was found, but no libYARP_math was detected, please recompile yarp

```

cc @traversaro @kouroshD @lrapetti @nunoguedelha

**Comment by kouroshD** [comment]
I tried tonight in my machine (macOS-Mojave) to build superbuild core and dynamic profiles. I could build them without any error.

**Comment by diegoferigo** [comment]
@claudia-lat Did you use a clean `build` folder? The default flag to enable the math library changed with YARP 3.2, and I suspect you're experiencing a problem related to the cmake cache.

**Comment by kouroshD** [comment]
As far as I know the `build` folder was clean.

**Comment by claudia-lat** [comment]
Yes, the build folder was clean.

**Comment by lrapetti** [comment]
I think it can be relevant the fact that the computer was updated from a fairly version of the OS (`Mountain Lion`) where all the dependencies were installed with an older version of `homebrew` and where not up-to-date. So, `homebrew` together with the dependencies were updated after moving to `Mojave`, but the process was not really clean I think.

**Comment by diegoferigo** [comment]
I have always struggled with such big updates (2012 -> 2019?). In these cases from my experience (if possible) wiping everything can prevent many future problems of leftovers in the OS.

**Comment by traversaro** [comment]
That specific error should go away by manually enabling the option `YARP_COMPILE_libYARP_math` in the YARP build.

**Comment by claudia-lat** [comment]
I've just installed from scratch (and in a brand new Mojave MAC laptop) the robotology-superbuild. I've compiled it with `ROBOTOLOGY_USES_MATLAB` OFF. It worked.  The error I had in the previous installation didn't appear anymore.

**Comment by traversaro** [comment]
So I guess we can  close the issue?

**Comment by claudia-lat** [comment]
> So I guess we can close the issue?

Yes. Closing it!
