### ISSUE TITLE
Fix compilation of ROBOLOGY_ENABLE_ICUB_HEAD  profile option on macOs

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#237]
At the moment, the ROBOLOGY_ENABLE_ICUB_HEAD option fails on macOs with a dragonfly related error, see https://github.com/robotology/robotology-superbuild/pull/234/checks?check_run_id=200516475 .

**Comment by traversaro** [comment]
Probably it is sufficient to add  https://brewformulas.org/Libdc1394 as a dependency.

**Comment by traversaro** [comment]
cc @kouroshD did you experience any problem like that?

**Comment by kouroshD** [comment]
No, it was fine for me. I did not have any problem.

**Comment by traversaro** [comment]
cc @nunoguedelha

**Comment by nunoguedelha** [comment]
@traversaro , so both the `superbuild` and `icub-main` Readmes should be updated right?

**Comment by traversaro** [comment]
Exactly.

**Comment by nunoguedelha** [comment]
I think we can also close this issue for now, considering https://github.com/robotology/robotology-superbuild/pull/268.

**Comment by traversaro** [comment]
As the option is now tested in macOS as part of the CI with https://github.com/robotology/robotology-superbuild/pull/276, I agree that we can close the issue.
