### ISSUE TITLE
FirmwareUpdater and a few other tools do not compile by default with option ROBOTOLOGY_ENABLE_ICUB_HEAD

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/robotology-superbuild#281]
The tools **canLoader, ethLoader, FirmwareUpdater, strainCalib, and strainCalibrationDataAcquisition** are not compiled if `ICUB_USE_icub_firmware_shared` is not set in the ICUB sub-project cmake.
Currently `ICUB_USE_icub_firmware_shared` is set to `OFF` by default.

@traversaro , this option is not well documented in `icub-main`, or if it is, that documentation is not easy to find. I suggest that we either:
- set `ICUB_USE_icub_firmware_shared` to `ON` through the flag `ROBOTOLOGY_ENABLE_ICUB_HEAD`,
- either document it in https://github.com/robotology/robotology-superbuild#icub-head.

**Comment by traversaro** [comment]
>  set `ICUB_USE_icub_firmware_shared` to `ON` through the flag `ROBOTOLOGY_ENABLE_ICUB_HEAD`

This seems the best option, at least w.r.t. consistency with the rest of superbuild options.
