### ISSUE TITLE
Setting YCM_TAG in XXXProjectsTag.cmake

### ISSUE THREAD

**Issue by drdanz** [robotology/robotology-superbuild#283]
Is there a reason why `YCM_TAG` is currently set in the main `CMakeLists.txt` and not in the `{Stable,Unstable}ProjectsTags.cmake` file?

https://github.com/robotology/robotology-superbuild/blob/f4c6a16527d2af534e45b51ab08bdb78c4ab45b2/CMakeLists.txt#L115

This makes it harder to test the YCM development branch...

**Comment by traversaro** [comment]
No reason at all, it just predates the `{Stable,Unstable}ProjectsTags.cmake` file by far, and it was there just because the bootstrapped YCM does not have a `BuildYCM.cmake` in which to keep this info. I am totally in favor of moving it in the `{Stable,Unstable}ProjectsTags.cmake`  file.
