### ISSUE TITLE
Links broken in doc/change-project-tags.md

### ISSUE THREAD

**Issue by xEnVrE** [robotology/robotology-superbuild#285]
Links to `cmake/ProjectTagsStable.cmake` and `cmake/ProjectTagsUnstable.cmake` in [doc/change-project-tags.md](https://github.com/robotology/robotology-superbuild/doc/change-project-tags.md) are broken.

They point to 

`https://github.com/robotology/robotology-superbuild/blob/master/doc/cmake/ProjectTagsStable.cmake`

and 

`https://github.com/robotology/robotology-superbuild/blob/master/doc/cmake/ProjectTagsUnstable.cmake` that do not exist.

**Comment by traversaro** [comment]
Thanks,  can you check if https://github.com/robotology/robotology-superbuild/pull/286 fixes the issue for you?

**Comment by xEnVrE** [comment]
That works!

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/robotology-superbuild/pull/286 .
