### ISSUE TITLE
Document the appendWindowsPath option in wsl.conf instead of manually sanitizing the path?

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#361]
Apparently, there is now a cleaner solution to the cross-talking of env variables from Windows to WSL (see https://github.com/robotology/robotology-superbuild#sanitize-enviroment-variables-for-wsl), described in  https://github.com/microsoft/WSL/issues/1493#issuecomment-580643734 . 
We should check if that works fine also for other env variables such as CMAKE_PREFIX_PATH, and eventually consider to document it in place of the existing solution documented in the robotology-superbuild README.

**Comment by Nicogene** [comment]
On wsl2 I had issued trying the bash command to cleanup the env variables(https://github.com/robotology/robotology-superbuild#sanitize-enviroment-variables-for-wsl)

On the other hand https://github.com/microsoft/WSL/issues/1493#issuecomment-580643734 worked for me
