### ISSUE TITLE
Add whole-body-estimators to robotology-superbuild

### ISSUE THREAD

**Issue by fjandrad** [robotology/robotology-superbuild#365]
Since codyco-modules is being deprecated, the super useful wholebodydynamics device was [transfered to whole-body-estimators](https://github.com/robotology/whole-body-estimators/pull/16).
Therefore, whole-body-estimators should be now installed by default when dynamics option is selected by robotology-superbuild.

**Comment by fjandrad** [comment]
cc @traversaro

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robotology-superbuild/pull/369 .
