### ISSUE TITLE
Windows build is currently broken on Stable and Unstable branches

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#366]
This is due to https://github.com/robotology/walking-controllers/issues/58 .

**Comment by traversaro** [comment]
This probably was fixed by https://github.com/robotology/walking-controllers/pull/59 , I restarted the build.

**Comment by traversaro** [comment]
The build still fails, see  https://github.com/robotology/walking-controllers/issues/58#issuecomment-600107149 .

**Comment by traversaro** [comment]
Hi @GiulioRomualdi, if you want I can provide a PR to walking-controllers to fix this, let me know if it is ok.

**Comment by GiulioRomualdi** [comment]
Working right now on it

**Comment by traversaro** [comment]
> 
> 
> Working right now on it

Great, thanks!

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/walking-controllers/pull/60 .

**Comment by GiulioRomualdi** [comment]
If you want to update the `TAG` in the superbuild this is the release: https://github.com/robotology/walking-controllers/releases/tag/v0.3.2

**Comment by traversaro** [comment]
> If you want to update the `TAG` in the superbuild this is the release: https://github.com/robotology/walking-controllers/releases/tag/v0.3.2

Thanks, the 2020.02 release is now done and we don't plan to update. The 0.3.2 can be a good candidate for the 2020.05 release.
