### ISSUE TITLE
Provide more details on Xcode usage in README 

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#37]
https://github.com/robotology/robotology-superbuild/pull/31#issuecomment-362313856

cc @nunoguedelha

**Comment by nunoguedelha** [comment]
@traversaro I can do a small contribution here if you wish...

**Comment by nunoguedelha** [comment]
@traversaro Ah just saw your other comment. I will update this ASAP.

**Comment by traversaro** [comment]
@nunoguedelha do you think the README still needs more details regarding Xcode? If not, I think we can close this issue.

**Comment by nunoguedelha** [comment]
@traversaro I'm taking a look now...

**Comment by nunoguedelha** [comment]
@traversaro I just created the PR.
