### ISSUE TITLE
Cleanup MATLAB docs

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#38]
Dealing with all the different variations of the Matlab install on users computer is typically the biggest bottleneck for new users installing the superbuild, as we saw with @gabrielenava and @ahmadgazar . 

Things to cleanup: 
* [ ]  Clarify how the CMake subprojects of the superbuild are actually finding Matlab. In particular, if the robotology is not able to find Matlab, the user has no guidance on how to setup its system to make sure that matlab is found. As of CMake 3.10 the FindMatlab.cmake is **not** checking any env variable such as `Matlab_ROOT_DIR` or `MATLAB_DIR`, the only reliable way to get CMake to detect matlab is to ensure that this call to `find_program` is able to find the matlab program:  https://github.com/Kitware/CMake/blob/v3.10.2/Modules/FindMatlab.cmake#L1035 . To make sure that find_program finds matlab, it is possible to check the search policy of `find_program` in CMake's docs : https://cmake.org/cmake/help/v3.8/command/find_program.html?highlight=i . In particular, adding (at least temporary) the directory in which matlab is contained in `PATH` or `CMAKE_PROGRAM_PATH` should do the trick. 
* [ ] Mention all the `LD_PRELOAD` problem, at least pointing to some exhaustive documentation on how to deal with it (see https://github.com/robotology/robotology-superbuild/issues/64).

**Comment by gabrielenava** [comment]
> Clarify how the CMake subprojects of the superbuild are actually finding Matlab. In particular, if the robotology is not able to find Matlab, the user has no guidance on how to setup its system to make sure that matlab is found. As of CMake 3.10 the FindMatlab.cmake is not checking any env variable such as Matlab_ROOT_DIR or MATLAB_DIR, the only reliable way to get CMake to detect matlab is to ensure that this call to find_program is able to find the matlab program: https://github.com/Kitware/CMake/blob/v3.10.2/Modules/FindMatlab.cmake#L1035 . To make sure that find_program finds matlab, it is possible to check the search policy of find_program in CMake's docs : https://cmake.org/cmake/help/v3.8/command/find_program.html?highlight=i . In particular, adding (at least temporary) the directory in which matlab is contained in PATH or CMAKE_PROGRAM_PATH should do the trick.

I think this has been done, am I right? At, lest, it seems so by looking at https://github.com/robotology/robotology-superbuild#system-dependencies-8

>Mention all the LD_PRELOAD problem, at least pointing to some exhaustive documentation on how to deal with it (see #64).

concerning this, there is the link to the [WBToolbox README](https://github.com/robotology/wb-toolbox/blob/master/README.md). See https://github.com/robotology/robotology-superbuild#start-matlab-from-the-terminal

@traversaro  do you think that what this is enough to close the issue?
