### ISSUE TITLE
Clean WB-Toolbox dependencies

### ISSUE THREAD

**Issue by diegoferigo** [robotology/robotology-superbuild#44]
The 3.0 release of `WB-Toolbox` dropped the `wholeBodyInterface` and `yarpWholeBodyInterface` dependencies. They can be removed from the superbuild.

**Comment by diegoferigo** [comment]
@traversaro @gabrielenava I remember we discussed f2f about a dependency which might prevent this drop, was it [mex-wholebodymodel](https://github.com/robotology/mex-wholebodymodel) (which is not included in this superbuild)?

**Comment by gabrielenava** [comment]
I think `mex-wholebodymodel` depends upon the `yarpWholeBodyInterface`, on the other hand the repo is currently not used.

**Comment by traversaro** [comment]
If you think you can manage the installation of `mex-wholebodymodel` outside the superbuild, I am ok in removing it.

**Comment by gabrielenava** [comment]
I'm ok with this

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robotology-superbuild/pull/125 (I guess).
