### ISSUE TITLE
Release 2020.08.patch-01

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#485]
Version to bump:
* YARP from v3.4.0 to v3.4.1
* YCM from v0.11.3 to v0.11.4 
* GazeboYARPPlugins from v3.5.0 to v3.5.1 (still needs to be released, see https://github.com/robotology/gazebo-yarp-plugins/pull/520) 
* icub-models from v1.17.0 to v1.17.1 (to fix the velocity control, see https://github.com/robotology/icub-models/pull/48)

**Comment by traversaro** [comment]
@pattacini do you want to add some fixes for icub-main ? In that case it would be great to to a patch release of icub-main.

**Comment by pattacini** [comment]
We may want to fix https://github.com/robotology/icub-main/issues/685.
Awaiting reply from @ale-git.

**Comment by traversaro** [comment]
> 
> 
> We may want to fix [robotology/icub-main#685](https://github.com/robotology/icub-main/issues/685).
> Awaiting a reply from @ale-git.

Ack, even if (at least on my side) there is no urgency in fixing https://github.com/robotology/icub-main/issues/685 .

**Comment by traversaro** [comment]
Yes, no problem! I just pinged you in the case you had some fix that you wanted to release, not because I wanted https://github.com/robotology/icub-main/issues/685 to be fixed anytime soon.

**Comment by traversaro** [comment]
The release has been tagged at [`v2020.08.patch-01`](https://github.com/robotology/robotology-superbuild/tree/v2020.08.patch-01) and autogenerated Windows binaries are available at https://github.com/robotology/robotology-superbuild/releases/tag/v2020.08.patch-01 . Unless there is a specific problems, I would close the issue.
