### ISSUE TITLE
Move to robotology?

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#5]
For tagging user/groups, it would be extremely convenient to have this repo already in robotology . 
As https://github.com/robotology-playground/robotology-superbuild/ is still used by the "old" robotology ADVR superbuild, I propose to move things forward we move this repo in robotology, keeping the existing disclaimer to warn users that the superbuild is still in alpha-phases. 

@drdanz what do you think?

**Comment by drdanz** [comment]
Fine with me, but let's discuss it f2f with ADVR guys before moving it

**Comment by traversaro** [comment]
Done.
