### ISSUE TITLE
Switch ROBOTOLOGY_USES_OCULUS to use repo https://github.com/robotology/yarp-device-ovrheadset

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#511]
It should be doable for 2020.11 .

**Comment by traversaro** [comment]
I am quite puzzled. The `ROBOTOLOGY_USES_OCULUS_SDK` does not does anything at the moment, and in YARP it does not enable the `ovrheadset` . How is this possible? How are we using it in the Oculus laptop? @kouroshD @S-Dafarra @GiulioRomualdi

**Comment by S-Dafarra** [comment]
I guess that until now, we were doing everything by hand

**Comment by traversaro** [comment]
> I guess that until now, we were doing everything by hand

Ack, in that case if somebody who did the setup could review the existing docs to see if they match what we actually do (that it was not the case until now, as we never wrote to enable manually the ovrheadset device) it would be great.
