### ISSUE TITLE
Remove icub-gazebo-wholebody? 

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#543]
I am not sure if someone is still using the models and worlds in https://github.com/robotology/icub-gazebo-wholebody . If someone does, please comment here. If no one will reply, we should consider removing the repo. 

cc @robotology/iit-dynamic-interaction-control @gabrielenava

**Comment by gabrielenava** [comment]
I don't use them anymore, maybe @Yeshasvitvs for the iCub standing up from the chair?

**Comment by Yeshasvitvs** [comment]
I am not using then repo models actively. @lrapetti please confirm if you are using this models for pRRI ?

**Comment by lrapetti** [comment]
> @lrapetti please confirm if you are using this models for pRRI ?

I am not using those models, so for me we can proceed removing it.
