### ISSUE TITLE
Add unicycle-footstep-planner, walking-controllers and their dependencies 

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#55]
Original title: add unicycle-footstep-planner
cc @S-Dafarra @DanielePucci

**Comment by S-Dafarra** [comment]
It is possible I misunderstood the meaning of this issue. I will try to add it soon!

**Comment by traversaro** [comment]
Great, modified the title of the issue. 
It would be great to also modify the Dynamics profile documentation to add a "Check your installation" section that would link a simple tutorial on how to run the walking demo in simulation.

**Comment by traversaro** [comment]
Now that https://github.com/robotology/capture-point-walking is available, I think it is possible to proceed.

Any volunteer?

**Comment by S-Dafarra** [comment]
I can try to deal with the ``Cmake`` stuff, but I would ask @GiulioRomualdi to fill the tutorial :grin:

**Comment by S-Dafarra** [comment]
See also https://github.com/robotology/unicycle-footstep-planner/issues/14

**Comment by traversaro** [comment]
@S-Dafarra great! Let me know if there are any problem.

**Comment by GiulioRomualdi** [comment]
Right now `qpOASES` is compiled by the `robotology-superbuild` only if `ROBOTOLOGY_USES_MATLAB` is set to `ON`
https://github.com/robotology/robotology-superbuild/blob/04e9aee50e4d8bc6601e588be18ec1bc45f2b03b/cmake/BuildqpOASES.cmake#L24-L29
However, it is needed by the `capture-point-walking`  module and this module does not require MATLAB (i.e. it can be installed inside `iCub-head`)

**Comment by S-Dafarra** [comment]
Noticed that :wink: Thanks!

**Comment by traversaro** [comment]
>  However, it is needed by the capture-point-walking module and this module does not require MATLAB (e.g. it can be installed inside iCub-head)

This will automatically handled if you list `qpOASES` in the `DEPENDS` of some project (such as `capture-point-walking`) for which then `find_or_build_package()` is listed in https://github.com/robotology/robotology-superbuild/blob/04e9aee50e4d8bc6601e588be18ec1bc45f2b03b/CMakeLists.txt#L120 .

**Comment by S-Dafarra** [comment]
See https://github.com/robotology/robotology-superbuild/pull/87

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robotology-superbuild/pull/87 .

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robotology-superbuild/pull/87 .
