### ISSUE TITLE
Regression in conda-forge Linux CI

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#552]
From https://github.com/robotology/robotology-superbuild/actions . 

Two days ago everything was working fine: 
* https://github.com/robotology/robotology-superbuild/runs/1514709988?check_suite_focus=true 

Yesterday instead something went wrong, and went wrong also in https://github.com/robotology/robotology-superbuild/pull/532 : https://github.com/robotology/robotology-superbuild/runs/1521342051?check_suite_focus=true 

The error is: 
~~~
Looking for: ['ace', 'asio', 'boost', 'eigen', 'gazebo', 'glew', 'glfw', 'gsl', 'ipopt', 'libjpeg-turbo', 'libmatio', 'libode', 'libxml2', 'opencv', 'pkg-config', 'portaudio', 'qt', 'sdl', 'sdl2', 'sqlite', 'tinyxml']

Encountered problems while solving.
Problem: package gazebo-11.0.0-h398b6f7_9 requires qt >=5.12.5,<5.13.0a0, but none of the providers can be installed
~~~

I briefly tried to replicate this locally, and it seems that instead conda is working fine, I spawned https://github.com/robotology/robotology-superbuild/pull/551 to check if this happens also on the CI.

**Comment by traversaro** [comment]
Cool, switching to conda as done in https://github.com/robotology/robotology-superbuild/pull/551 fixes the problem on Linux, and it creates a new problem on macOS: https://github.com/robotology/robotology-superbuild/pull/551/checks?check_run_id=1527274310 .

**Comment by traversaro** [comment]
Indeed, the problem is in mamba. 
~~~
mamba install -c conda-forge cmake compilers make ninja pkg-config ace asio boost eigen gazebo glew glfw gsl ipopt libjpeg-turbo libmatio libode libxml2 opencv pkg-config portaudio qt sdl sdl2 sqlite tinyxml
~~~
fails with the previous error (see ci job https://github.com/robotology/robotology-superbuild/runs/1529533907), while :

~~~
 conda install -c conda-forge cmake compilers make ninja pkg-config ace asio boost eigen gazebo glew glfw gsl ipopt libjpeg-turbo libmatio libode libxml2 opencv pkg-config portaudio qt sdl sdl2 sqlite tinyxml
~~~
works fine (see ci job https://github.com/robotology/robotology-superbuild/runs/1530469671).

I saw that a new release of mamba was released recently (https://github.com/conda-forge/mamba-feedstock/pull/87), so let's see if the problem is solved in 0.7.5 before reporting the problem in mamba.

**Comment by wolfv** [comment]
I just tried 

```
mamba create -c conda-forge cmake compilers make ninja pkg-config ace asio boost eigen gazebo glew glfw gsl ipopt libjpeg-turbo libmatio libode libxml2 opencv pkg-config portaudio qt sdl sdl2 sqlite tinyxml
```

on linux, and that worked fine.

**Comment by traversaro** [comment]
> @traversaro unfortunately this release of mamba doesn't address any kind of solving issues :/

Thanks for the hint!

**Comment by wolfv** [comment]
Sorry, it's got to be 

```
mamba create cmake compilers make ninja pkg-config ace asio boost eigen gazebo glew glfw gsl ipopt libjpeg-turbo libmatio libode libxml2 opencv pkg-config portaudio qt sdl sdl2 sqlite tinyxml -c conda-forge -n testenv --dry-run
```

**Comment by traversaro** [comment]
> Did you also try mamba create ...? If you are installing into the base-environment, there might be an incompatibility somewhere.

In theory the setup-miniconda is not installing in the base-environement, but rather everything in an environment called `test` . Now that I think of, this means that I am not installing `mamba` in the `base`  environment, but just in `test`  one, and I guess that could create problem. I will investigate more.

**Comment by traversaro** [comment]
Indeed, the problem will be fixed by https://github.com/robotology/robotology-superbuild/pull/553 that avoiding to manually install mamba, but rather is following the official setup-miniconda docs: https://github.com/conda-incubator/setup-miniconda#example-6-mamba . 

Thanks @wolfv for the help, as usual.

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robotology-superbuild/pull/553 .
