### ISSUE TITLE
Add https://github.com/dic-iit/matlab-whole-body-simulators 

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#576]
cc @nunoguedelha

**Comment by traversaro** [comment]
Relevant documentation: https://github.com/robotology/robotology-superbuild/blob/master/doc/developers-faqs.md#how-to-add-a-new-package .

**Comment by nunoguedelha** [comment]
## Critical information on the repo `matlab-whole-body-simulator`
- Profile **ROBOTOLOGY_ENABLE_DYNAMICS**, option **ROBOTOLOGY_USES_MATLAB**.
- available on GitHub.
- Does not use CMake.
