### ISSUE TITLE
Add whole-body-controllers

### ISSUE THREAD

**Issue by gabrielenava** [robotology/robotology-superbuild#58]
The repo that contains the latest working version of the iCub torque controllers for balancing is [whole-body-controllers](https://github.com/robotology-playground/whole-body-controllers) and it should be added to the superbuild instead of [WBIToolbox-controllers](https://github.com/robotology-playground/WBI-Toolbox-controllers), that I think we can deprecate.

**Comment by gabrielenava** [comment]
Ping

**Comment by traversaro** [comment]
I think it make sense. Feel free to open a pull request with the proposed changes.

**Comment by gabrielenava** [comment]
Done in this PR https://github.com/robotology/robotology-superbuild/pull/62

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/robotology-superbuild/pull/62 .
