### ISSUE TITLE
ICUB Compilation failure on Windows due to SDL libraries silently not found

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#602]
Compiling the robotology-superbuild on Windows following exactly the instructions in the README results in the following error:

~~~
 iCubSkinGui.vcxproj -> C:\src\robotology-superbuild\build\src\ICUB\bin\Release\iCubSkinGui.exe
libifcoremd.lib(for_main.obj) : error LNK2019: unresolved external symbol MAIN__ referenced in function main [C:\src\robotology-superbuild\build\src\ICUB\src\simulators\iCubSimulation\iCub_SIM.vcxproj]
C:\src\robotology-superbuild\build\src\ICUB\bin\Release\iCub_SIM.exe : fatal error LNK1120: 1 unresolved externals [C:\src\robotology-superbuild\build\src\ICUB\src\simulators\iCubSimulation\iCub_SIM.vcxproj]
  iKinCartesianSolver.vcxproj -> C:\src\robotology-superbuild\build\src\ICUB\bin\Release\iKinCartesianSolver.exe
  iKinGazeCtrl.vcxproj -> C:\src\robotology-superbuild\build\src\ICUB\bin\Release\iKinGazeCtrl.exe
  icubmod.vcxproj -> C:\src\robotology-superbuild\build\src\ICUB\lib\Release\icubmod.lib
  imageBlender.vcxproj -> C:\src\robotology-superbuild\build\src\ICUB\bin\Release\imageBlender.exe
  imageCropper.vcxproj -> C:\src\robotology-superbuild\build\src\ICUB\bin\Release\imageCropper.exe
  imageSplitter.vcxproj -> C:\src\robotology-superbuild\build\src\ICUB\bin\Release\imageSplitter.exe
MSVCRT.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\src\robotology-superbuild\build\src\ICUB\src\tools\joystickCheck\joystickCheck.vcxproj]
C:\src\robotology-superbuild\build\src\ICUB\bin\Release\joystickCheck.exe : fatal error LNK1120: 1 unresolved externals [C:\src\robotology-superbuild\build\src\ICUB\src\tools\joystickCheck\joystickCheck.vcxproj]
MSVCRT.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\src\robotology-superbuild\build\src\ICUB\src\tools\joystickCtrl\joystickCtrl.vcxproj]
~~~

The problem here is that vcpkg install some libraries not in `C:\robotology\vcpkg\installed\x64-windows\lib`, but rather in `C:\robotology\vcpkg\installed\x64-windows\lib\manual-link`. This directory unfortunately is not searched  if the `CMAKE_PREFIX_PATH` is set to `C:\robotology\vcpkg\installed\x64-windows`, so to ensure that the CMake works correctly it is necessary to add `C:\robotology\vcpkg\installed\x64-windows\lib\manual-link` to `CMAKE_LIBRARY_PATH` or use the `CMAKE_TOOLCHAIN_FILE` of vcpkg, that is however not documented.  If this does not happe, the `find_package(SDL)` silently fails and produces an invalid value for `SDL_LIBRARY` , that will not contain the necessary `SDLmain.lib` library. The tricky aspect is that once the CMake project has been configured the `SDL_LIBRARY` value will be set to an invalid value, its value will be cached so the only possibility is either to delete the `SDL_LIBRARY` variable, or clean the build. 

The CI did not catch the problem as there we are using `CMAKE_TOOLCHAIN_FILE` (and that is a problem).

What I really wonder about is how comes this problem was never reported. My assumption is that probably power users disseminate the fact that `CMAKE_TOOLCHAIN_FILE` should be used, even if that was not documented in the superbuild README, and this knowledge was passed from user to user in some way. Just as a check, for people that recently installed the robotology-superbuild on Windows, did you followed the README instructions verbatim or did you passed the `CMAKE_TOOLCHAIN_FILE` option to the CMake configuration?

@S-Dafarra @GiulioRomualdi @isorrentino @Yeshasvitvs @lrapetti @vpunithreddy

**Comment by traversaro** [comment]
The problem did not affected conda as in that case there is no such strange directory `lib/manual-link`.

**Comment by S-Dafarra** [comment]
> . My assumption is that probably power users disseminate the fact that `CMAKE_TOOLCHAIN_FILE` should be used, even if that was not documented in the superbuild README,

It seems documented in https://github.com/robotology/robotology-superbuild-dependencies-vcpkg:

> To install , you just need to download either `vcpkg-robotology.zip` or `vcpkg-robotology-with-gazebo.zip` and extract it in the `C:/` directory.
> The archive contains a `robotology` directory, that will be available in your system as `C:/robotology` .
> 
> To use then vcpkg libraries, you need to configure your CMake projects to use the vcpkg's 
> toolchain as `CMAKE_TOOLCHAIN_FILE`, for example by configuring the projects as:  
> ~~~
> cmake -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/robotology/vcpkg/scripts/buildsystems/vcpkg.cmake ..
> ~~~

I would argue that https://github.com/robotology/robotology-superbuild#system-libraries does not describe in detail how to use the archive, referring then to the documentation of ``robotology-superbuild-dependencies-vcpkg``

> For instructions on how to correctly use this archives, please refer to documentation of the robotology-superbuild-dependencies-vcpkg repo.

**Comment by traversaro** [comment]
Ahh, that is a good point. It is also explicitly explain in https://github.com/robotology/robotology-superbuild#superbuild-3 : 
> Once you cloned the repository, you can generate the Visual Studio solution using the CMake GUI, by using as a generator the appropriate Visual Studio version, and the 64 bit as platform, and specifying the vcpkg CMake toolchain as discussed in the previous section. 

This explains why other users did not experience this, thanks! In any case, even if you don't specify the toolchain this will be fixed by https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/40 .
