### ISSUE TITLE
Create a manually dispatched GitHub Action to do a new release

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#636]
Doing a  new release is not a time intensive action (a few minutes every 3 months) but it is quite error prone, as we keep forgetting steps (see https://github.com/robotology/robotology-superbuild/issues/635) and there are some steps that are intrinsically prone to errors (for example, when tagging a new release on the releases/yyyy.mm branch, the default setting of the GitHub UI is to do tag the release on `master` branch, and it is quite easy to forget to switch to releases/yyyy.mm branch). 

For this reason, it may be convenient to create a GitHub Action to do the steps documented in https://github.com/robotology/robotology-superbuild/blob/v2021.02/doc/developers-faqs.md#how-to-do-a-new-release automatically.

**Comment by traversaro** [comment]
@Nicogene is preparing something on this, according to verbal communication.

**Comment by drdanz** [comment]
FYI YARP stable releases are done 95% using a GH action now:
https://github.com/robotology/yarp/blob/master/.github/workflows/tag.yml

It's still not ready for "feature" releases, and it still needs some operation to be done manually, but it is still saving me lots of time.

**Comment by traversaro** [comment]
> 
> 
> FYI YARP stable releases are done 95% using a GH action now:
> https://github.com/robotology/yarp/blob/master/.github/workflows/tag.yml
> 
> It's still not ready for "feature" releases, and it still needs some operation to be done manually, but it is still saving me lots of time.

Super cool!
