### ISSUE TITLE
Wrong name for the Build<package>.cmake for matio-cpp

### ISSUE THREAD

**Issue by Nicogene** [robotology/robotology-superbuild#678]
The cmake name of `matio-cpp` is actually `matioCpp`, then this https://github.com/robotology/robotology-superbuild/blob/master/cmake/Buildmatio-cpp.cmake should be named `BuildmatioCpp.cmake` and `matio-cpp` has to be replaced in other `find_or_build_package` calls.

cc @traversaro @S-Dafarra

**Comment by S-Dafarra** [comment]
Is it ok to have the two names different?

**Comment by traversaro** [comment]
Good point!

**Comment by traversaro** [comment]
> Is it ok to have the two names different?

In the normal workflow that we typically use is not a big difference, having two different names may be problematic if you want to configure the superbuild to use an external matioCpp as find_or_build_package(matio-cpp) will not actually look for the `matioCpp` package.
