### ISSUE TITLE
Support build of ICUB python bindings

### ISSUE THREAD

**Issue by xEnVrE** [robotology/robotology-superbuild#691]
I noticed that if one enables `ROBOTOLOGY_USES_PYTHON` the python bindings of the package `ICUB` are not built.

Is there a specific reason for that or is it something that can be supported?

The options for enabling it on `ICUB` are `-DICUB_COMPILE_BINDINGS:BOOL=ON -DCREATE_PYTHON:BOOL=ON`.

I can open a PR in case.

Thank you

**Comment by traversaro** [comment]
I think it is simply due to the fact that nobody added it, feel free to open a PR, thanks!
