### ISSUE TITLE
superbuild does not build with CMake 3.20

### ISSUE THREAD

**Issue by kouroshD** [robotology/robotology-superbuild#717]
I have a fresh clone of robotology-superbuild. When I try to build it, It returns the following error:

```
CMake Error: File C:/Program Files/CMake/share/cmake-3.20/Modules/RepositoryInfo.txt.in does not exist.
CMake Error at build/CMakeFiles/ExternalProject.cmake:2517 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  build/CMakeFiles/ExternalProject.cmake:3264 (_ep_add_download_command)
  build/CMakeFiles/YCMEPHelper.cmake:1049 (ExternalProject_Add)
  cmake/Buildrobots-configuration.cmake:19 (ycm_ep_helper)
  build/install/share/YCM/modules/FindOrBuildPackage.cmake:215 (include)
  cmake/RobotologySuperbuildLogic.cmake:17 (find_or_build_package)
  CMakeLists.txt:62 (include)
```
I have checked the CMake folder, in fact the requested file is in `C:\Program Files\CMake\share\cmake-3.20\Modules\ExternalProject\RepositoryInfo.txt.in`, therefore the folder `ExternalProject` is missing.

 @traversaro Do you have any suggestion to fix this problem?!

**Comment by traversaro** [comment]
On which platform you are? How are you installing dependencies?

**Comment by kouroshD** [comment]
On Windows, I used the vcpkg dependencies. Meanwhile, I am updating the explanations there are you can find in this branch:
https://github.com/kouroshD/robotology-superbuild/tree/tmp/fixExplanation

**Comment by traversaro** [comment]
Both vcpkg and conda-forge-based CI on Windows are using CMake 3.20 (vcpkg 3.20.1, conda 3.20.2) and seem to be working fine, so i wonder where is the problem. Which specific version did you installed (i.e. what is the output of `cmake --version`)? How did you installed it?

**Comment by kouroshD** [comment]
I uninstalled and installed again using CMake installer, and it was working fine. I could install robotology.

Thanks @traversaro
