### ISSUE TITLE
Why not use environment activation in `install_robotology_packages.m`

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/robotology-superbuild#721]
Hi @traversaro , I have a couple of questions regarding the script `install_robotology_packages.m`, in https://github.com/robotology/robotology-superbuild/blob/029fdd35a705c9d8d8a14b4663b0158ecd1d9314/scripts/install_robotology_packages.m#L86-L99.

We are not using the environment activation/deactivation feature. Is this for avoiding to modify the `.bashrc` or `.bash_profile`?

The Conda install adds a code snippet at the end of the `.bashrc`, which is required for supporting the activation/deactivation features. But that code snippet could be executed in a script separately from the `.bashrc` no? in such case we would reduce the impact on the user environment to the terminal where conda is being run.

I mention this because having the update of the environment variables hardcoded in yet another script is less maintainable than just doing `conda deactivate` and `conda activate`...

**Comment by nunoguedelha** [comment]
Still, out of curiosity, what about doing on Matlab command line `system('source ./condaInitialize')`, where `condaInitialize` has the content:
```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/nunoguedelha/miniforge3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/nunoguedelha/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/Users/nunoguedelha/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/nunoguedelha/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```
That would allow to use activate/deactivate from Matlab no? Unless it doesn't work on Windows...

**Comment by traversaro** [comment]
I did not checked, but in general `system` spawns a new child process, and the environment variables set by the child process are not propagated to the parent process (the MATLAB interpreter). 

However, for the time being to mitigate the need to modify those path we could simply minimize the path that we add. For example, perhaps in cases like https://github.com/robotology/robotology-superbuild/pull/722 we could simple install the examples in `<install_prefix>/mex` rather then adding a new directory  `<install_prefix>/mex/+wbc/examples` , unless a new directories is strictly necessary (for example for Similink libraries with their ` slblocks.m`).

**Comment by traversaro** [comment]
@nunoguedelha do you think we can close this issue? If we want to improve the situation (like storing the metadata on which env variables need to be set for each program) we can do that by opening another issue.

**Comment by traversaro** [comment]
@nunoguedelha feel free to re-open if you think this is the case.
