### ISSUE TITLE
Missing YARP_ROBOT_NAME discussion in icub-models repo 

### ISSUE THREAD

**Issue by FabioBergonti** [robotology/robotology-superbuild#73]
@traversaro
In this [link](https://github.com/robotology-playground/icub-models) there are no information about how to define the name of iCub model

**Comment by traversaro** [comment]
Hi @FabioBergonti , I missed this issue originally. 
You mean that a table similar to the one in https://github.com/robotology-playground/icub-model-generator#generated-models should also be in `icub-models` ?

**Comment by traversaro** [comment]
If we have no idea what this issue is tracking, I think we can close the issue. If anyone has any idea what this issue was about, he/she can open a new issue or re-open this one.
