### ISSUE TITLE
Stop supporting Gazebo 9/10 and only support Gazebo 11? 

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#812]
The `ROBOTOLOGY_USES_GAZEBO` is currently tested against both Gazebo 9 and Gazebo 11. To simplify mantainance, I would like to stop supporting Gazebo 9, and only support Gazebo 11 at some point in the future (2021.11 perhaps?).

I would like to know if there is any blocker for this, or if there are teams that are not using Gazebo 11, but rather are still using Gazebo 9 or 10.

As additional info, Gazebo 10 already reached end of support, while Gazebo 9 will reach end of support in 2023, while Gazebo 11 will reach end of support in 2025, see http://gazebosim.org/#status . 

At the ROS level (see http://gazebosim.org/tutorials/?tut=ros_wrapper_versions) Gazebo11 is the version fully supported since ROS Noetic (for ROS 1) and ROS Foxy (for ROS 2). Earler versions (ROS Melodic, ROS Dashing/Eloquent) support Gazebo11 but it is not the default version used in them, so you can use Gazebo 11, but you need to rebuilt any ROS binary package that dependes on Gazebo.

cc @robotology/edpr-developers @robotology/iit-dynamic-interaction-control @drdanz @xEnVrE @randaz81

**Comment by arrenglover** [comment]
@Iaxama what version we are using for EDPR work?

**Comment by Iaxama** [comment]
> @Iaxama what version we are using for EDPR work?

We use gazebo 11

**Comment by traversaro** [comment]
@Yeshasvitvs @lrapetti not sure if https://github.com/robotology/gazebo-yarp-plugins/issues/494 is still a problem.

**Comment by Yeshasvitvs** [comment]
I am not certain about it as I haven't been using Gazebo for a while. May be @HosameldinMohamed can share some details ?

**Comment by drdanz** [comment]
Debian testing has gazebo 11, so not a problem for me...

**Comment by lrapetti** [comment]
> @Yeshasvitvs @lrapetti not sure if [robotology/gazebo-yarp-plugins#494](https://github.com/robotology/gazebo-yarp-plugins/issues/494) is still a problem.

I am not sure either since I have actually never used it. I saw @paolo-viceconte was involved in the discussion, maybe has some more recent experience?

**Comment by paolo-viceconte** [comment]
> > @Yeshasvitvs @lrapetti not sure if [robotology/gazebo-yarp-plugins#494](https://github.com/robotology/gazebo-yarp-plugins/issues/494) is still a problem.
> 
> I am not sure either since I have actually never used it. I saw @paolo-viceconte was involved in the discussion, maybe has some more recent experience?

Not really. I only used the external wrench plugin for quick tests but then that activity has been dropped, so no recent updates wrt what has been documented in the issue above.

**Comment by traversaro** [comment]
Example of issue that emerge with older version of Gazebo: https://github.com/ignitionrobotics/ign-math/issues/214 .

**Comment by traversaro** [comment]
A major advantage of switching to Gazebo 11 is that we could ship our models using SDF 1.7, avoiding several problems we had in the past with complex SDF 1.6 models (especially SDF 1.6 models that included SDF 1.7 models) in Gazebo 11, see https://github.com/osrf/gazebo/issues/2728, https://github.com/robotology/icub-models/issues/67 and https://github.com/osrf/gazebo/issues/2739 .

**Comment by traversaro** [comment]
Wider announcement done in https://github.com/robotology/community/discussions/534 .

**Comment by traversaro** [comment]
Done in https://github.com/robotology/gazebo-yarp-plugins/pull/575 and https://github.com/robotology/robotology-superbuild/pull/873 .

**Comment by traversaro** [comment]
Closing as this was announced in https://github.com/robotology/community/discussions/534 .
