### ISSUE TITLE
Stop supporting Homebrew in robotology-superbuild Continuous Integration and direct macOS users to conda?

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#842]
Homebrew CI is extremely fragile, for several reasons. The main one, is that there is no easy way in Homebrew to be able to install the same package you installed a few days before, basically making really difficult to achieve reproducibility, that is quite critical in scientific research. 

To give an idea, this are just the issue related to Homebrew CI failures just in the last few months: 
* https://github.com/robotology/robotology-superbuild/issues/841
* https://github.com/robotology/robotology-superbuild/issues/826
* https://github.com/robotology/robotology-superbuild/issues/789
* https://github.com/robotology/robotology-superbuild/issues/704
* https://github.com/robotology/robotology-superbuild/issues/693
* https://github.com/robotology/robotology-superbuild/issues/571
* https://github.com/robotology/robotology-superbuild/issues/568
* https://github.com/robotology/robotology-superbuild/issues/565
* https://github.com/robotology/robotology-superbuild/issues/490
* https://github.com/robotology/robotology-superbuild/issues/476
* https://github.com/robotology/robotology-superbuild/issues/440
* https://github.com/robotology/robotology-superbuild/issues/879
* https://github.com/robotology/robotology-superbuild/pull/899#issuecomment-934541671, https://github.com/actions/virtual-environments/issues/4228
* https://github.com/robotology/robotology-superbuild/issues/919
* https://github.com/robotology/robotology-superbuild/issues/1017

Continuously dealing with these CI failures is quite demanding. At the same time, during the last year I think that `conda-forge` and the related channels (`robostack` and `robotology`) reached a level of maturity for which they are able to provide to macOS users easily installable and reproducible binaries (see . 

At this point I think a reasonable plan for the future, unless someone step in to volunteer mantainance of the Homebrew CI, is to **stop supporting the use of Homebrew in the robotology-superbuild CI and docs**, and direct macOS users to use conda instead. 

To clarify, this does not mean that single software projects part of the robotology organization cannot support Homebrew: anyone can support Homebrew, simply there will be no CI at the robotology-superbuild level to check that all packages are able to compile w.r.t. to compatible versions or branches of each other.

Ideally we would like all regular robotology-superbuild macOS user to be proficient with conda before that day, but I guess that unless there is a reason for doing so, people will not go out of their Homebrew-using comfort zone, and I know this process take time, so better to start off.

As usual for these kind of issues, any kind of feedback is extremely welcome.

**Comment by pattacini** [comment]
I'm in favor 👍🏻

**Comment by lrapetti** [comment]
As MacOS/homebrew user, I think that if it can make more reproducible the installation robotology dependency w.r.t. homebrew, I have no problem in moving to conda after testing it.

**Comment by traversaro** [comment]
After that the regression in GitHub Actions/Homebrew always continue, I decided. The Homebrew CI will be **removed** from the robotology-superbuild on the 15th of May, 2023.

**Comment by lrapetti** [comment]
> As MacOS/homebrew user, I think that if it can make more reproducible the installation robotology dependency w.r.t. homebrew, I have no problem in moving to conda after testing it.

As a follow-up of this comment, I switched to `conda` dependencies since a while and I have never encountered issues.

**Comment by traversaro** [comment]
> After that the regression in GitHub Actions/Homebrew always continue, I decided. The Homebrew CI will be **removed** from the robotology-superbuild on the 15th of May, 2023.

PR that will be merged on Monday: https://github.com/robotology/robotology-superbuild/pull/1407 .

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robotology-superbuild/pull/1407 .
