### ISSUE TITLE
``yarpmotorgui`` does not start on Windows with ``conda`` dependencies

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/robotology-superbuild#895]
I tried to launch ``yarpmotorgui`` but I got the following error
![image](https://user-images.githubusercontent.com/18591940/135295907-4806549c-c2e6-47cb-9358-de6e0bcce0b2.png)

I also tried to run ``yarpmanager`` but nothing showed up. 

I guess there is some path missing.

@Nicogene any idea?

**Comment by Nicogene** [comment]
I tried on my pc(Windows as well), and it seems that it doesn't start without any error messages.
Probably it is somehow related to #871 and #883 , unfortunately I have not a fresh conda installation, then probably I miss those fixes

**Comment by S-Dafarra** [comment]
I did not understand, do you have the same issue or not?

**Comment by Nicogene** [comment]
> I did not understand, do you have the same issue or not?

I cannot start it, but I don't get any message, but I don't have a fresh setup on windows, so it may be another issue.
`yarpmanager` starts without problem instead.

**Comment by S-Dafarra** [comment]
Actually, I applied manually the workaround of https://github.com/robotology/robotology-superbuild/pull/883 by manually copying the file ``qt.conf`` from ``mambaforge\envs\robsub\`` to ``robotology-superbuild\build\install\bin`` and it started working.

We were using a release version of the superbuild and it worked. I guess that patch has not been released yet.

Thanks @Nicogene 

Closing

**Comment by traversaro** [comment]
fyi @sgiraz that could be interested in this as well

**Comment by sgiraz** [comment]
Thanks @traversaro, if necessary I'll take a look at it. 🙏🏻
