### ISSUE TITLE
CI Failures October 2021

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#897]
The following jobs are now failing, see https://github.com/robotology/robotology-superbuild/actions/runs/1307389708 :

* ❌ `[docker:Tags:Default@ubuntu:bionic@Debug]`
   * **Reason:**  `blocktest` master branch now does not compile anymore on 18.04/Bionic with apt due to the use of filesystem, see https://github.com/robotology/blocktest/commit/65ccf23b4254d41e99babe51e138917d2b1a608b#diff-4d19f6c5be5264a89fc03f09b18025f2dfcc071e8249f7361d50adc26aee3cbfR16 cc @Nicogene @triccyx 
   * **Proposed Action:** Drop `ROBOTOLOGY_ENABLE_ROBOT_TESTING` support on Ubuntu 18.04 with apt

* ❌ `[Tags:Unstable@ubuntu-18.04@Release]`
   * **Reason:** YARP changes now require SWIG 4.0, see https://github.com/robotology/yarp/pull/2720
   * **Proposed Action:** Drop `ROBOTOLOGY_USES_PYTHON` support on Ubuntu 18.04 with apt

* ❌ `[conda:Tags:Default@ubuntu-latest@Release] `
   * **Reason:** Not sure, probably a gym-ignition compilation error? See https://github.com/robotology/robotology-superbuild/issues/898 for the detailed error
   * **Proposed Action:** Not sure @diegoferigo any idea? Drop `ROBOTOLOGY_USES_IGNITION` support for now?

**Comment by Nicogene** [comment]
I am ok with the proposed action(at least for bindings and testing profile)
