### ISSUE TITLE
provide python code for skin sensor from icub simulator

### ISSUE THREAD

**Issue by ArfnZl** [robotology/robotology-superbuild#963]
hello sir
i tried many times to write code,but my code is not working please provide python code for tectile skin sensor from icub simulator thanks
import yarp
import numpy as np
import matplotlib.pyplot as plt
import sys
from mpl_toolkits.mplot3d import Axes3D
import scipy.interpolate
yarp.Network.init()
 

right_hand = yarp.Port()
prop = yarp.Property();
right_hand.open("/python/right_hand")
yarp.Network.connect('/icubSim/skin/right_hand_comp','/python/right_hand')
read.(/reader /icubSim/skin/right_hand_comp
)

**Comment by ArfnZl** [comment]
please sir correct my code ..the last line my code is giving errors..ports is connected but reading part is not working

**Comment by traversaro** [comment]
Hi @ArfnZl, I guess you are refererring to the old iCub_SIM simulator, right? Could you report the system you are on, the version of robotology-superbuild you are using and the options with which you compiled it?

> the last line my code is giving errors..

Can you report the error that your code is returning?

**Comment by traversaro** [comment]
Hi @ArfnZl, did you solved your problem?

**Comment by ArfnZl** [comment]
No my problem is not solving  please  help to solve this problem i am
waiting for your reply thank you

**Comment by traversaro** [comment]
Hi @ArfnZl, it would be great if you could answer the question asked in https://github.com/robotology/robotology-superbuild/issues/963#issuecomment-997440101, otherwise it would be difficult to help you.

**Comment by ArfnZl** [comment]
Dear i am using the latest

**Comment by traversaro** [comment]
@ArfnZl, please answer all questions, thanks!

**Comment by ArfnZl** [comment]
![Screenshot_2022-01-09-22-12-06-88](https://user-images.githubusercontent.com/83446699/148692909-01ed4001-0b35-4310-b1c3-624a797960c7.png)

**Comment by ArfnZl** [comment]
![Uploading Screenshot_2022-01-09-22-12-28-00.png…]()

**Comment by ArfnZl** [comment]
@traversaro 
Please  help

**Comment by ArfnZl** [comment]
@traversaro can you provide any example of reading data  from tactile  sensors in icub simulator  through python code

**Comment by ArfnZl** [comment]
@traversaro 
The problem is not with port just give you an example of Python code skin sensor reading

**Comment by traversaro** [comment]
@ArfnZl you can find some examples for the Python bindings of YARP in https://github.com/robotology/yarp/tree/master/bindings/python/examples and https://github.com/s4hri/yarp-python-tutorials . If you follow them, you should be able to understand how to read data from any YARP port, including the ports that publish skin sensor data on the iCub_SIM simulator.

**Comment by traversaro** [comment]
Hi @ArfnZl, feel free to open new issues if you have more doubts.
