### ISSUE TITLE
How to connect tectile sensors in icub simulator through  python code 

### ISSUE THREAD

**Issue by ArfnZl** [robotology/robotology-superbuild#985]
Please  provide any example  to connect tectile sensor in icub silmulator hands through  python

**Comment by ArfnZl** [comment]
The problem is not with port just give you an example of Python code skin sensor reading

**Comment by traversaro** [comment]
Hi @ArfnZl, as this issue seems to be a duplicate of https://github.com/robotology/robotology-superbuild/issues/963, I will close it. Sorry for this, but please avoid to open duplicate issue for the same problem.
