### ISSUE TITLE
Document use of Visual Studio 2022

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#993]
VS2022 should be supported, but it is not clearly documented.

**Comment by traversaro** [comment]
cc @isorrentino

**Comment by jwillemsen** [comment]
Be aware that ACE/TAO are not tested with vs2022, see https://github.com/DOCGroup/ACE_TAO/issues/1661

**Comment by traversaro** [comment]
> Be aware that ACE/TAO are not tested with vs2022, see DOCGroup/ACE_TAO#1661

Thanks! If we noticed anything of strange, we will report it. 

However, notice that here we are discussing about using ace from conda-forge (so compiled with VS2017) with a program compiled with VS2022, so it is a bit of a mixed situation.

**Comment by traversaro** [comment]
Anyhow this was fixed in https://github.com/robotology/robotology-superbuild/pull/995 .
