### ISSUE TITLE
Missing libi2c-dev apt dependency? 

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#999]
Some iCub models connect to the head's Bosch IMU bno055 IMU via i2c. To do so, they use YARP's device [`imuBosch_BNO055`](https://github.com/robotology/yarp/tree/v3.6.0/src/devices/imuBosch_BNO055) . To do so, on Debian systems you need to install the `libi2c-dev` dependency. However, this dependency is not listed anywhere.

**Comment by traversaro** [comment]
@Nicogene did you ever had problems related to this?

**Comment by Nicogene** [comment]
From what I remember no, but probably because in the [iCub OS images already contain it](https://icub-tech-iit.github.io/documentation/icub_operating_systems/download/)
